spring:
  application:
    name: eureka-service

server:
  port: 8087

eureka:
  client:
    registerWithEureka: false
    fethcRegistry: false
    service-url:
      defaultZone: http://localhost:8087/eureka
    server:
      waitTimeInMsWhenSyncEmpty: 0


zuul:
  prefix: /api
  routes:
    mongo-service:
      path: /mongo-service/**
      url: http://localhost:8080
    stock-service:
      path: /stock-service/**
      url: http://localhost:8304
